// <auto-generated />
namespace FileCabinetApp
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
        
    public class FileCabinetService
    {
        private readonly List<FileCabinetRecord> list = new List<FileCabinetRecord>();

        public int CreateRecord(string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            if (string.IsNullOrWhiteSpace(firstName))
            {
                throw new ArgumentNullException(firstName);
            }

            if (string.IsNullOrWhiteSpace(lastName))
            {
                throw new ArgumentNullException(lastName);
            }

            if (firstName.Length < 2 || firstName.Length > 60)
            {
                throw new ArgumentException(firstName);
            }

            if (lastName.Length < 2 || lastName.Length > 60)
            {
                throw new ArgumentException(lastName);
            }

            if (dateOfBirth < new DateTime(1950, 01, 01) || dateOfBirth > DateTime.Now)
            {
                throw new ArgumentException("Wrong dateOfBirth");
            }

            if (height < 30 || height > 250)
            {
                throw new ArgumentException(height.ToString());
            }

            if (weight <= 0)
            {
                throw new ArgumentException(weight.ToString());
            }

            if (gender != 'm' && gender != 'f' && gender != 'a')
            {
                throw new ArgumentException(gender.ToString());
            }

            var record = new FileCabinetRecord
            {
                Id = this.list.Count + 1,
                FirstName = firstName,
                LastName = lastName,
                DateOfBirth = dateOfBirth,
                Height = height,
                Weight = weight,
                Gender = gender,
            };

            this.list.Add(record);
            
            return record.Id;
        }

        public void ListRecords()
        {
            foreach (FileCabinetRecord record in this.list)
            {
                record.ShowRecord();
            }
        }

        public bool IsRecordExist(int id)
        {
            if (this.list.Exists(x => x.Id == id))
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public void EditRecord(int id, string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            FileCabinetRecord record = this.list.Find(x => x.Id == id);
            if (string.IsNullOrWhiteSpace(firstName))
            {
                throw new ArgumentNullException(firstName);
            }

            if (string.IsNullOrWhiteSpace(lastName))
            {
                throw new ArgumentNullException(lastName);
            }

            if (firstName.Length < 2 || firstName.Length > 60)
            {
                throw new ArgumentException(firstName);
            }

            if (lastName.Length < 2 || lastName.Length > 60)
            {
                throw new ArgumentException(lastName);
            }

            if (dateOfBirth < new DateTime(1950, 01, 01) || dateOfBirth > DateTime.Now)
            {
                throw new ArgumentException("Wrong dateOfBirth");
            }

            if (height < 30 || height > 250)
            {
                throw new ArgumentException(height.ToString());
            }

            if (weight <= 0)
            {
                throw new ArgumentException(weight.ToString());
            }

            if (gender != 'm' && gender != 'f' && gender != 'a')
            {
                throw new ArgumentException(gender.ToString());
            }

            record.FirstName = firstName;
            record.LastName = lastName;
            record.DateOfBirth = dateOfBirth;
            record.Height = height;
            record.Weight = weight;
            record.Gender = gender;
        }

        public FileCabinetRecord[] FindByFirstName(string firstName) 
        {
            var result = from rec in this.list
                         where rec.FirstName.ToUpper() == firstName.ToUpper()
                         select rec;
            return result.ToArray();
        }

        public FileCabinetRecord[] FindByLastName(string firstName)
        {
            var result = from rec in this.list
                         where rec.LastName.ToUpper() == firstName.ToUpper()
                         select rec;
            return result.ToArray();
        }

        public FileCabinetRecord[] FindByDateOfBirth(string firstName)
        {
            var result = from rec in this.list
                         where $"{rec.DateOfBirth.Year}-{rec.DateOfBirth.ToString("MMM", CultureInfo.GetCultureInfo("en-us"))}-{rec.DateOfBirth.Day}".ToUpper() == firstName.ToUpper()
                         select rec;
            return result.ToArray();
        }

        public FileCabinetRecord[] GetRecords()
        {
            // TODO: добавьте реализацию метода
            return Array.Empty<FileCabinetRecord>();
        }

        public int GetStat()
        {
            // TODO: добавьте реализацию метода
            return this.list.Count;
        }
    }
}
