// <auto-generated />
namespace FileCabinetApp
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
        
    /// <summary>
    /// Class that realizes all the services of the main class
    /// </summary>
    public class FileCabinetService
    {
        private readonly List<FileCabinetRecord> list = new List<FileCabinetRecord>();

        private readonly Dictionary<string, List<FileCabinetRecord>> firstNameDictionary = new Dictionary<string, List<FileCabinetRecord>>();

        private readonly Dictionary<string, List<FileCabinetRecord>> lastNameDictionary = new Dictionary<string, List<FileCabinetRecord>>();

        private readonly Dictionary<string, List<FileCabinetRecord>> dateOfBirthDictionary = new Dictionary<string, List<FileCabinetRecord>>();

        /// <summary>
        /// Transforms DateTime to string in special format
        /// </summary>
        /// <param name="date">Date to transform</param>
        /// <returns>String format of date</returns>
        public static string GetDateAsString(DateTime date)
        {
            return $"{date.Year}-{date.ToString("MMM", CultureInfo.GetCultureInfo("en-us"))}-{date.Day}".ToUpper();
        }

        /// <summary>
        /// Adds record to a chosen dictionary
        /// </summary>
        /// <param name="dictionary">Chosen dictionary</param>
        /// <param name="value">Key for a record</param>
        /// <param name="record">Record to add</param>
        public void AddToDictionary(Dictionary<string, List<FileCabinetRecord>> dictionary, string value, FileCabinetRecord record)
        {
            if (dictionary.ContainsKey(value))
            {
                dictionary[value].Add(record);
            }
            else
            {
                dictionary.Add(value, new List<FileCabinetRecord> { record });
            }
        }

        /// <summary>
        /// Removes a record from a chosen dictionary
        /// </summary>
        /// <param name="dictionary">A chosen dictionary</param>
        /// <param name="value">Key for a record</param>
        /// <param name="id">Record's id</param>
        public void RemoveFromDictionary(Dictionary<string, List<FileCabinetRecord>> dictionary, string value, int id)
        {
            FileCabinetRecord itemToDelete = dictionary[value].SingleOrDefault(x => x.Id == id);
            dictionary[value].Remove(itemToDelete);
        }

        /// <summary>
        /// Creates new record
        /// </summary>
        /// <param name="firstName">FirstName</param>
        /// <param name="lastName">LastName</param>
        /// <param name="dateOfBirth">DateOfBirth</param>
        /// <param name="height">Height</param>
        /// <param name="weight">Weight</param>
        /// <param name="gender">Gender</param>
        /// <returns>Id of a record</returns>
        public int CreateRecord(string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            if (string.IsNullOrWhiteSpace(firstName))
            {
                throw new ArgumentNullException(firstName);
            }

            if (string.IsNullOrWhiteSpace(lastName))
            {
                throw new ArgumentNullException(lastName);
            }

            if (firstName.Length < 2 || firstName.Length > 60)
            {
                throw new ArgumentException(firstName);
            }

            if (lastName.Length < 2 || lastName.Length > 60)
            {
                throw new ArgumentException(lastName);
            }

            if (dateOfBirth < new DateTime(1950, 01, 01) || dateOfBirth > DateTime.Now)
            {
                throw new ArgumentException("Wrong dateOfBirth");
            }

            if (height < 30 || height > 250)
            {
                throw new ArgumentException(height.ToString());
            }

            if (weight <= 0)
            {
                throw new ArgumentException(weight.ToString());
            }

            if (gender != 'm' && gender != 'f' && gender != 'a')
            {
                throw new ArgumentException(gender.ToString());
            }

            int id = this.list.Count + 1;
            
            this.list.Add(new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));

            this.AddToDictionary(this.firstNameDictionary, firstName.ToUpper(), new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));
            this.AddToDictionary(this.lastNameDictionary, lastName.ToUpper(), new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));
            string dateAsString = GetDateAsString(dateOfBirth);
            this.AddToDictionary(this.dateOfBirthDictionary, dateAsString, new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));

            return id;
        }

        /// <summary>
        /// Prints all the existing records
        /// </summary>
        public void ListRecords()
        {
            foreach (FileCabinetRecord record in this.list)
            {
                record.ShowRecord();
            }
        }

        /// <summary>
        /// Checks is a record with this id is exist
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>Is a record exist or no</returns>
        public bool IsRecordExist(int id)
        {
            if (this.list.Exists(x => x.Id == id))
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        /// <summary>
        /// Edits an existing record
        /// </summary>
        /// <param name="id">Id</param>
        /// <param name="firstName">FirstName</param>
        /// <param name="lastName">LastName</param>
        /// <param name="dateOfBirth">DateOfBirth</param>
        /// <param name="height">Height</param>
        /// <param name="weight">Weight</param>
        /// <param name="gender">Gender</param>
        public void EditRecord(int id, string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            FileCabinetRecord record = this.list.Find(x => x.Id == id);
            if (string.IsNullOrWhiteSpace(firstName))
            {
                throw new ArgumentNullException(firstName);
            }

            if (string.IsNullOrWhiteSpace(lastName))
            {
                throw new ArgumentNullException(lastName);
            }

            if (firstName.Length < 2 || firstName.Length > 60)
            {
                throw new ArgumentException(firstName);
            }

            if (lastName.Length < 2 || lastName.Length > 60)
            {
                throw new ArgumentException(lastName);
            }

            if (dateOfBirth < new DateTime(1950, 01, 01) || dateOfBirth > DateTime.Now)
            {
                throw new ArgumentException("Wrong date of birth");
            }

            if (height < 30 || height > 250)
            {
                throw new ArgumentException(height.ToString());
            }

            if (weight <= 0)
            {
                throw new ArgumentException(weight.ToString());
            }

            if (gender != 'm' && gender != 'f' && gender != 'a')
            {
                throw new ArgumentException(gender.ToString());
            }

            this.RemoveFromDictionary(this.firstNameDictionary, record.FirstName.ToUpper(), id);
            this.RemoveFromDictionary(this.lastNameDictionary, record.LastName.ToUpper(), id);
            string dateAsString = GetDateAsString(record.DateOfBirth);
            this.RemoveFromDictionary(this.dateOfBirthDictionary, dateAsString, id);
            
            this.AddToDictionary(this.firstNameDictionary, firstName.ToUpper(), new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));
            this.AddToDictionary(this.lastNameDictionary, lastName.ToUpper(), new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));
            dateAsString = GetDateAsString(dateOfBirth);
            this.AddToDictionary(this.dateOfBirthDictionary, dateAsString, new FileCabinetRecord(id, firstName, lastName, dateOfBirth, height, weight, gender));

            record.UpdateRecord(firstName, lastName, dateOfBirth, height, weight, gender);
        }

        /// <summary>
        /// Finds all the records with chosen first name
        /// </summary>
        /// <param name="firstName">FirstName</param>
        /// <returns>Array of finded records</returns>
        public FileCabinetRecord[] FindByFirstName(string firstName) 
        {
            /*var result = from rec in this.list
                         where rec.FirstName.ToUpper() == firstName.ToUpper()
                         select rec;
            return result.ToArray();*/ //Realization with LINQ
            if (firstNameDictionary.ContainsKey(firstName.ToUpper()) && this.firstNameDictionary[firstName.ToUpper()].Count > 0)
            {
                return this.firstNameDictionary[firstName.ToUpper()].ToArray();
            }
            else
            {
                Console.WriteLine($"There are no records with first name {firstName}");
                return null;
            }
        }

        /// <summary>
        /// Finds all the records withchosen last name
        /// </summary>
        /// <param name="lastName">LastName</param>
        /// <returns>Array of finded records</returns>
        public FileCabinetRecord[] FindByLastName(string lastName)
        {
            if (lastNameDictionary.ContainsKey(lastName.ToUpper()) && this.lastNameDictionary[lastName.ToUpper()].Count > 0)
            {
                return this.lastNameDictionary[lastName.ToUpper()].ToArray();
            }
            else
            {
                Console.WriteLine($"There are no records with last name {lastName}");
                return null;
            }
        }

        /// <summary>
        /// Finds all the records with chosen date of birth
        /// </summary>
        /// <param name="dateOfBirth">DateOfBirth</param>
        /// <returns>Array of finded records</returns>
        public FileCabinetRecord[] FindByDateOfBirth(string dateOfBirth)
        {
            if (dateOfBirthDictionary.ContainsKey(dateOfBirth.ToUpper()) && this.dateOfBirthDictionary[dateOfBirth.ToUpper()].Count > 0)
            {
                return this.dateOfBirthDictionary[dateOfBirth.ToUpper()].ToArray();
            }
            else
            {
                Console.WriteLine($"There are no records with date of birth {dateOfBirth}");
                return null;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public FileCabinetRecord[] GetRecords()
        {
            // TODO: добавьте реализацию метода
            return Array.Empty<FileCabinetRecord>();
        }

        /// <summary>
        /// Returns amount of records
        /// </summary>
        /// <returns>Amount of records</returns>
        public int GetStat()
        {
            return this.list.Count;
        }
    }
}
