// <auto-generated />
namespace FileCabinetApp
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class FileCabinetRecord
    {
        public FileCabinetRecord(int id, string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            DateOfBirth = dateOfBirth;
            Height = height;
            Weight = weight;
            Gender = gender;
        }

        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public DateTime DateOfBirth { get; set; }

        public short Height { get; set; }

        public decimal Weight { get; set; }

        public char Gender { get; set; }

        public void ShowRecord()
        {
            Console.WriteLine($"#{Id}, {FirstName}, {LastName}, " +
                    $"{DateOfBirth.Year}-{DateOfBirth.ToString("MMM", CultureInfo.GetCultureInfo("en-us"))}-{DateOfBirth.Day}, " +
                    $"{Height}cm, {Weight}kg, {Gender}");
        }

        public void UpdateRecord(string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            FirstName = firstName;
            LastName = lastName;
            DateOfBirth = dateOfBirth;
            Height = height;
            Weight = weight;
            Gender = gender;
        }
    }
}
