// <auto-generated />
namespace FileCabinetApp
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Xml.Serialization;

    /// <summary>
    /// FileCabinetRecord class
    /// </summary>
    //[Serializable]
    [XmlRoot("records")]
    [XmlType(TypeName = "record")]
    public class FileCabinetRecord
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public FileCabinetRecord()
        { }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="id">Id.</param>
        /// <param name="firstName">FirstName.</param>
        /// <param name="lastName">LastName.</param>
        /// <param name="dateOfBirth">DateOfBirth.</param>
        /// <param name="height">Height.</param>
        /// <param name="weight">Weight.</param>
        /// <param name="gender">Gender.</param>
        public FileCabinetRecord(int id, string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            DateOfBirth = dateOfBirth;
            Height = height;
            Weight = weight;
            Gender = gender;
        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="id">Id.</param>
        /// <param name="data">Data for a record.</param>
        public FileCabinetRecord(int id, DataForRecord data)
        {
            Id = id;
            FirstName = data.FirstName;
            LastName = data.LastName;
            DateOfBirth = data.DateOfBirth;
            Height = data.Height;
            Weight = data.Weight;
            Gender = data.Gender;
        }

        [XmlAttribute]
        public int Id { get; set; }

        public string FirstName { get; set; }
        
        public string LastName { get; set; }

        public DateTime DateOfBirth { get; set; }

        public short Height { get; set; }

        public decimal Weight { get; set; }

        public char Gender { get; set; }

        /// <summary>
        /// Prints information about this record.
        /// </summary>
        public void ShowRecord()
        {
            Console.WriteLine($"#{Id}, {FirstName}, {LastName}, " +
                    $"{DateOfBirth.Year}-{DateOfBirth.ToString("MMM", CultureInfo.GetCultureInfo("en-us"))}-{DateOfBirth.Day}, " +
                    $"{Height}cm, {Weight}kg, {Gender}");
        }

        /// <summary>
        /// Updates information about this record.
        /// </summary>
        /// <param name="firstName">FirstName.</param>
        /// <param name="lastName">LastName.</param>
        /// <param name="dateOfBirth">DateOfBirth.</param>
        /// <param name="height">Height.</param>
        /// <param name="weight">Weight.</param>
        /// <param name="gender">Gender.</param>
        public void UpdateRecord(string firstName, string lastName, DateTime dateOfBirth, short height, decimal weight, char gender)
        {
            FirstName = firstName;
            LastName = lastName;
            DateOfBirth = dateOfBirth;
            Height = height;
            Weight = weight;
            Gender = gender;
        }

        /// <summary>
        /// Updates information about this record.
        /// </summary>
        /// <param name="newData">New data for a record.</param>
        public void UpdateRecord(DataForRecord newData)
        {
            UpdateRecord(newData.FirstName, newData.LastName, newData.DateOfBirth, newData.Height, newData.Weight, newData.Gender);
        }
    }
}
